version: '3'
services:
  jwt_service:
    build: ./jwt_service
    ports:
      - "3000:3000"
    env_file:
      - ./jwt_service/.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  crud_service:
    build: ./crud_service
    ports:
      - "4000:4000"
    env_file:
      - ./crud_service/.env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cruddb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  postgres-data:
